# Generated by Django 5.1.2 on 2025-06-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=200)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('AS', 'Asignada'), ('CO', 'Completada'), ('CA', 'Cancelada')], default='AS', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='CoeficienteCultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase_crecimiento', models.CharField(max_length=50)),
                ('kc_valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dias_desde_siembra', models.IntegerField(help_text='Días desde siembra para esta fase')),
                ('et_minima', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='ET mínima (mm/día)')),
                ('et_maxima', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='ET máxima (mm/día)')),
                ('humedad_optima_min', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Humedad óptima mínima (%)')),
                ('humedad_optima_max', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Humedad óptima máxima (%)')),
            ],
            options={
                'ordering': ['dias_desde_siembra'],
            },
        ),
        migrations.CreateModel(
            name='Cosechas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(null=True)),
                ('precioUnidad', models.IntegerField(null=True)),
                ('cantidadTotal', models.FloatField(blank=True, null=True)),
                ('valorTotal', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Cultivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True, unique=True)),
                ('activo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Desechos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialBeneficioCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('costo_insumos', models.IntegerField(default=0)),
                ('total_mano_obra', models.IntegerField(default=0)),
                ('total_costos', models.IntegerField(default=0)),
                ('total_ventas', models.IntegerField(default=0)),
                ('beneficio', models.IntegerField(default=0)),
                ('relacion_beneficio_costo', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Historial Beneficio Costo',
                'verbose_name_plural': 'Historiales Beneficio Costo',
                'db_table': 'historial_beneficio_costo',
            },
        ),
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.TextField(max_length=150)),
                ('precio', models.IntegerField()),
                ('compuestoActivo', models.CharField(max_length=20, null=True)),
                ('contenido', models.FloatField(null=True)),
                ('fichaTecnica', models.ImageField(blank=True, null=True, upload_to='insumos/')),
                ('unidades', models.IntegerField()),
                ('totalGramos', models.IntegerField(blank=True, null=True)),
                ('cantidadGramos', models.IntegerField(blank=True, null=True)),
                ('valorTotalInsumos', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=30)),
                ('unidades', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Salarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('monto', models.IntegerField()),
                ('horas', models.FloatField()),
                ('monto_minutos', models.FloatField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'activo'), ('inactivo', 'inactivo')], default='activo', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TiempoActividadControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo', models.IntegerField(verbose_name='Cantidad de tiempo')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('valorTotal', models.IntegerField(editable=False, verbose_name='Valor total')),
            ],
            options={
                'verbose_name': 'Registro de Tiempo',
                'verbose_name_plural': 'Registros de Tiempo',
            },
        ),
        migrations.CreateModel(
            name='TipoActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='TiposDesecho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadesMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('abreviatura', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('MASA', 'MASA'), ('VOLUMEN', 'VOLUMEN')], default='MASA', max_length=30)),
                ('equivalenciabase', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UnidadesTiempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('equivalenciaMinutos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UsosInsumos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadProducto', models.IntegerField()),
                ('costoUsoInsumo', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precioUnitario', models.IntegerField()),
                ('fecha', models.DateField(auto_now=True)),
                ('cantidad', models.IntegerField()),
                ('descuento', models.IntegerField(null=True)),
                ('valorTotal', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
