# Generated by Django 5.1.2 on 2025-06-04 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finanzas', '0001_initial'),
        ('trazabilidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividades',
            name='fk_Plantacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trazabilidad.plantaciones'),
        ),
    ]
