# Generated by Django 5.1.2 on 2025-06-04 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finanzas', '0002_initial'),
        ('sanidad', '0001_initial'),
        ('trazabilidad', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actividades',
            name='fk_Usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cosechas',
            name='fk_Plantacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trazabilidad.plantaciones'),
        ),
        migrations.AddField(
            model_name='cultivos',
            name='fk_Especie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trazabilidad.especies'),
        ),
        migrations.AddField(
            model_name='coeficientecultivo',
            name='cultivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanzas.cultivos'),
        ),
        migrations.AddField(
            model_name='actividades',
            name='fk_Cultivo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.cultivos'),
        ),
        migrations.AddField(
            model_name='desechos',
            name='fk_Plantacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trazabilidad.plantaciones'),
        ),
        migrations.AddField(
            model_name='historialbeneficiocosto',
            name='fk_Cultivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_beneficio_costo', to='finanzas.cultivos'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='fk_Herramienta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trazabilidad.herramientas'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='fk_Insumo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.insumos'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='fk_UsoHerramienta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trazabilidad.usosherramientas'),
        ),
        migrations.AddField(
            model_name='tiempoactividadcontrol',
            name='fk_actividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.actividades'),
        ),
        migrations.AddField(
            model_name='tiempoactividadcontrol',
            name='fk_control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sanidad.controles'),
        ),
        migrations.AddField(
            model_name='tiempoactividadcontrol',
            name='fk_salario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.salarios'),
        ),
        migrations.AddField(
            model_name='actividades',
            name='fk_TipoActividad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.tipoactividad'),
        ),
        migrations.AddField(
            model_name='desechos',
            name='fk_TipoDesecho',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.tiposdesecho'),
        ),
        migrations.AddField(
            model_name='insumos',
            name='fk_UnidadMedida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.unidadesmedida'),
        ),
        migrations.AddField(
            model_name='cosechas',
            name='fk_UnidadMedida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.unidadesmedida'),
        ),
        migrations.AddField(
            model_name='tiempoactividadcontrol',
            name='fk_unidadTiempo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.unidadestiempo'),
        ),
        migrations.AddField(
            model_name='usosinsumos',
            name='fk_Actividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.actividades'),
        ),
        migrations.AddField(
            model_name='usosinsumos',
            name='fk_Control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sanidad.controles'),
        ),
        migrations.AddField(
            model_name='usosinsumos',
            name='fk_Insumo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.insumos'),
        ),
        migrations.AddField(
            model_name='usosinsumos',
            name='fk_UnidadMedida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.unidadesmedida'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='fk_UsoInsumo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.usosinsumos'),
        ),
        migrations.AddField(
            model_name='ventas',
            name='fk_Cosecha',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.cosechas'),
        ),
        migrations.AddField(
            model_name='ventas',
            name='fk_UnidadMedida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.unidadesmedida'),
        ),
        migrations.AddIndex(
            model_name='historialbeneficiocosto',
            index=models.Index(fields=['fk_Cultivo', 'fecha_registro'], name='historial_b_fk_Cult_daf807_idx'),
        ),
    ]
