# Generated by Django 5.1.2 on 2025-06-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usosinsumos',
            name='costoUsoInsumo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
