# Generated by Django 5.1.2 on 2025-06-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0004_alter_usosinsumos_costousoinsumo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='precioUnitario',
        ),
        migrations.AddField(
            model_name='cosechas',
            name='valorGramo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
