# Generated by Django 5.1.2 on 2025-06-04 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trazabilidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('descripcion', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='plaga/')),
            ],
        ),
        migrations.CreateModel(
            name='ProductosControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('precio', models.IntegerField()),
                ('compuestoActivo', models.CharField(max_length=20)),
                ('fichaTecnica', models.TextField()),
                ('contenido', models.IntegerField()),
                ('tipoContenido', models.CharField(max_length=10)),
                ('unidades', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='tipoPlaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('descripcion', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='tipoPlaga/')),
            ],
        ),
        migrations.CreateModel(
            name='TiposControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UsoProductosControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadProducto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Afecciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaEncuentro', models.DateField()),
                ('estado', models.CharField(choices=[('ST', 'ST'), ('EC', 'EC'), ('EL', 'EL')], default='ST', max_length=30)),
                ('fk_Plantacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trazabilidad.plantaciones')),
            ],
        ),
        migrations.CreateModel(
            name='Controles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fechaControl', models.DateField(auto_now_add=True)),
                ('fk_Afeccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sanidad.afecciones')),
            ],
        ),
    ]
