# Generated by Django 5.1.2 on 2025-06-04 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sanidad', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='controles',
            name='fk_Usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='afecciones',
            name='fk_Plaga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sanidad.plaga'),
        ),
        migrations.AddField(
            model_name='plaga',
            name='fk_Tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sanidad.tipoplaga'),
        ),
        migrations.AddField(
            model_name='controles',
            name='fk_TipoControl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sanidad.tiposcontrol'),
        ),
        migrations.AddField(
            model_name='usoproductoscontrol',
            name='fk_Control',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sanidad.controles'),
        ),
        migrations.AddField(
            model_name='usoproductoscontrol',
            name='fk_ProductoControl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sanidad.productoscontrol'),
        ),
    ]
