# Generated by Django 5.1.2 on 2025-06-04 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15, unique=True)),
                ('descripcion', models.TextField()),
                ('latI1', models.FloatField(null=True, unique=True)),
                ('longI1', models.FloatField(null=True, unique=True)),
                ('latS1', models.FloatField(null=True, unique=True)),
                ('longS1', models.FloatField(null=True, unique=True)),
                ('latI2', models.FloatField(null=True, unique=True)),
                ('longI2', models.FloatField(null=True, unique=True)),
                ('latS2', models.FloatField(null=True, unique=True)),
                ('longS2', models.FloatField(null=True, unique=True)),
                ('estado', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Eras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('latI1', models.FloatField(null=True, unique=True)),
                ('longI1', models.FloatField(null=True, unique=True)),
                ('latS1', models.FloatField(null=True, unique=True)),
                ('longS1', models.FloatField(null=True, unique=True)),
                ('latI2', models.FloatField(null=True, unique=True)),
                ('longI2', models.FloatField(null=True, unique=True)),
                ('latS2', models.FloatField(null=True, unique=True)),
                ('longS2', models.FloatField(null=True, unique=True)),
                ('fk_lote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='electronica.lote')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('TEM', 'Temperatura'), ('LUM', 'Iluminación'), ('HUM_A', 'Humedad Ambiental'), ('VIE', 'Velocidad del Viento'), ('HUM_T', 'Humedad del Terreno'), ('PH', 'Nivel de PH'), ('LLUVIA', 'Lluvia')], max_length=6)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('umbral_maximo', models.DecimalField(blank=True, decimal_places=2, help_text='Valor máximo permitido para este sensor', max_digits=10, null=True)),
                ('umbral_minimo', models.DecimalField(blank=True, decimal_places=2, help_text='Valor mínimo permitido para este sensor', max_digits=10, null=True)),
                ('fk_eras', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensores', to='electronica.eras')),
                ('fk_lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensores', to='electronica.lote')),
            ],
        ),
    ]
