# Generated by Django 5.1.2 on 2025-06-04 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('electronica', '0001_initial'),
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Herramientas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_Lote', models.IntegerField()),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=200)),
                ('unidades', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('valorTotal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TiposEspecie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.TextField(max_length=400)),
                ('img', models.ImageField(blank=True, null=True, upload_to='tiposespecie/')),
            ],
        ),
        migrations.CreateModel(
            name='Semilleros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidades', models.IntegerField()),
                ('fechasiembra', models.DateField()),
                ('fechaestimada', models.DateField()),
                ('fk_Cultivo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.cultivos')),
            ],
        ),
        migrations.CreateModel(
            name='Plantaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidades', models.IntegerField()),
                ('fechaSiembra', models.DateField()),
                ('creado', models.DateTimeField(auto_now=True)),
                ('fk_Cultivo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.cultivos')),
                ('fk_Era', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='electronica.eras')),
                ('fk_semillero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trazabilidad.semilleros')),
            ],
        ),
        migrations.CreateModel(
            name='Especies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.TextField(max_length=400)),
                ('img', models.ImageField(blank=True, null=True, upload_to='especies/')),
                ('tiempocrecimiento', models.CharField(choices=[('perennes', 'Perennes'), ('semiperennes', 'Semiperennes'), ('transitorio', 'Transitorio')], default='perennes', max_length=15)),
                ('fk_tipoespecie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trazabilidad.tiposespecie')),
            ],
        ),
        migrations.CreateModel(
            name='UsosHerramientas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidades', models.IntegerField(default=0)),
                ('fk_Actividad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.actividades')),
                ('fk_Herramienta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trazabilidad.herramientas')),
            ],
        ),
    ]
