# Generated by Django 5.1.2 on 2025-06-11 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanidad', '0002_initial'),
        ('trazabilidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usosherramientas',
            name='fk_Control',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sanidad.controles'),
        ),
    ]
