# Generated by Django 5.1.2 on 2025-06-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='admin',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correoElectronico',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'admin'), ('instructor', 'instructor'), ('pasante', 'pasante'), ('aprendiz', 'aprendiz'), ('visitante', 'visitante')], max_length=12),
        ),
    ]
